name: Aliyun Signin
on:
schedule:
# 每天国际时间 17:20 运行一次，中国时间 01:20
-cron: "20 17 米 * *
workflow dispatch:
jobs:
signin:
name: Aliyun Signin
runs-on: ubuntu-latest
steps:
- uses: ImYrS/aliyun-auto-signin@mainwith:
REFRESH TOKENS: $ f secrets.REFRESH TOKENS }}GP_TOKEN: $ff secrets .GP TOKEN}}PUSH TYPES:TELEGRAM
TELEGRAM BOT_TOKEN: ${{ secrets.TELEGRAM BOT_TOKEN }}
TELEGRAM_CHAT_ID: ${{ serets.TELEGRAM_CHAT_ID }}
